package com.ebooks.elevate.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.ebooks.elevate.entity.BudgetVO;

public interface BudgetRepo extends JpaRepository<BudgetVO, Long> {

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    ROW_NUMBER() OVER (ORDER BY accountcode) AS `ELGLS.No`,\r\n"
			+ "    accountname AS `ELGL`,\r\n"
			+ "    accountcode AS `ELGLCode`,\r\n"
			+ "    natureofaccount AS `NLDN/CR`,\r\n"
			+ "    MAX(CASE WHEN month = 'January' THEN amount ELSE 0 END) AS 'January',\r\n"
			+ "    MAX(CASE WHEN month = 'February' THEN amount ELSE 0 END) AS 'February',\r\n"
			+ "    MAX(CASE WHEN month = 'March' THEN amount ELSE 0 END) AS 'March',\r\n"
			+ "    MAX(CASE WHEN month = 'April' THEN amount ELSE 0 END) AS 'April',\r\n"
			+ "    MAX(CASE WHEN month = 'May' THEN amount ELSE 0 END) AS 'May',\r\n"
			+ "    MAX(CASE WHEN month = 'June' THEN amount ELSE 0 END) AS 'June',\r\n"
			+ "    MAX(CASE WHEN month = 'July' THEN amount ELSE 0 END) AS 'July',\r\n"
			+ "    MAX(CASE WHEN month = 'August' THEN amount ELSE 0 END) AS 'August',\r\n"
			+ "    MAX(CASE WHEN month = 'September' THEN amount ELSE 0 END) AS 'September',\r\n"
			+ "    MAX(CASE WHEN month = 'October' THEN amount ELSE 0 END) AS 'October',\r\n"
			+ "    MAX(CASE WHEN month = 'November' THEN amount ELSE 0 END) AS 'November',\r\n"
			+ "    MAX(CASE WHEN month = 'December' THEN amount ELSE 0 END) AS 'December'\r\n"
			+ "FROM budget where year=?2 and orgid=?1 and client=?3 and clientcode=?4 \r\n"
			+ "GROUP BY accountname, accountcode, natureofaccount\r\n"
			+ "ORDER BY accountcode")
	Set<Object[]> getClientBudgetDetails(Long orgId, String year, String client, String clientCode);

	@Query(nativeQuery = true,value = "select * from budget where orgid=?1 and clientcode=?2 and year=?3 and month=?4 and maingroup=?5 and subgroupcode=?6 and accountcode=?7")
	BudgetVO getBudgetDetails(Long orgId, String clientCode, String year, String month, String mainGroup,
			String subGroupCode, String accountCode);

	@Query(nativeQuery = true,value = "select g.maingroup,g.subgroup,g.subgroupcode,g.accountcode,g.accountname,g.natureofaccount,g.quater,sum(g.currentYear)currentYear,sum(g.previousYear)previousYear from(\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,quater,sum(amount) currentYear,0 previousYear from budget where orgid=?1 and clientcode=?4 and year=?2\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,natureofaccount,accountname,quater \r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,quater,0 currentYear,sum(amount)previousYear from budget where orgid=?1 and clientcode=?4 and year=?3\r\n"
			+ "group by maingroup,subgroup,natureofaccount,subgroupcode,accountcode,accountname,quater) g where g.maingroup=?5 and g.subgroup=?6 group by g.maingroup,g.subgroup,g.natureofaccount,g.subgroupcode,g.accountcode,g.accountname,g.quater \r\n"
			+ "order by g.quater asc")
	Set<Object[]> getELBudgetDetails(Long orgId, String finyear, String previousYear, String clientCode,
			String mainGroupName, String subGroupCode);

	@Query(nativeQuery = true,value = "SELECT \r\n"
			+ "    a.maingroup,\r\n"
			+ "    a.subgroup,\r\n"
			+ "    a.subgroupcode,\r\n"
			+ "    a.accountcode,\r\n"
			+ "    a.accountname,\r\n"
			+ "    a.natureofaccount,\r\n"
			+ "    ROUND(SUM(a.budget), 2) AS budget,\r\n"
			+ "    ROUND(SUM(a.actual), 2) AS actual,\r\n"
			+ "    ROUND(SUM(a.PY), 2) AS PY,\r\n"
			+ "    ROUND(SUM(a.budgetYTD), 2) AS budgetYTD,\r\n"
			+ "    ROUND(SUM(a.ActYTD), 2) AS ActYTD,\r\n"
			+ "    ROUND(SUM(a.PyYTD), 2) AS PyYTD,\r\n"
			+ "    ROUND(SUM(a.fullBudget), 2) AS fullBudget,\r\n"
			+ "    ROUND(\r\n"
			+ "        (SUM(a.ActYTD) / \r\n"
			+ "        (SELECT monthsequence FROM budget WHERE year=?3 AND month=?5 GROUP BY monthsequence) * 12),\r\n"
			+ "        2\r\n"
			+ "    ) AS Estimate,\r\n"
			+ "    ROUND(SUM(a.fullPY), 2) AS fullPY\r\n"
			+ "FROM (\r\n"
			+ "    select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,sum(amount) budget,0 actual,0 PY,0 budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,0 fullPY from budget where orgid=?1 and clientcode=?2 and year=?3 and month=?5\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,natureofaccount,accountname \r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,sum(amount)actual,0 PY,0 budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,0 fullPY from previousyearactual where orgid=?1 and clientcode=?2 and year=?3 and month=?5  group by maingroup,subgroup,natureofaccount,subgroupcode,accountcode,accountname\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,sum(amount)PY,0 budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,0 fullPY from previousyearactual where orgid=?1 and clientcode=?2 and year=?4 and month=?5  group by maingroup,subgroup,natureofaccount,subgroupcode,accountcode,accountname\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,sum(amount)budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,0 fullPY from budget where orgid=?1 and clientcode=?2 and year=?3  and monthsequence<=(select monthsequence from budget where year=?3 and month=?5 group by monthsequence)\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,natureofaccount,accountname,quater\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,0 budgetYTD,sum(amount) ActYTD,0 PyYTD,0 fullBudget,0 fullPY from previousyearactual where orgid=?1 and clientcode=?2 and year=?3 and monthsequence<=(select monthsequence from previousyearactual where year=?3 and month=?5 group by monthsequence)\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,0 budgetYTD,0 ActYTD,sum(amount) PyYTD,0 fullBudget,0 fullPY from previousyearactual where orgid=?1 and clientcode=?2 and year=?4 and monthsequence<=(select monthsequence from previousyearactual where year=?4 and month=?5 group by monthsequence)\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,0 budgetYTD,0 ActYTD,0 PyYTD,sum(amount)fullBudget,0 fullPY from budget a where a.orgid=?1 and a.clientcode=?2 and a.year=?3\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,0 budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,sum(amount) fullPY from previousyearactual a where a.orgid=?1 and a.clientcode=?2 and a.year=?4\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount\r\n"
			+ ") a where a.maingroup=?6 and a.subgroup=?7\r\n"
			+ "GROUP BY \r\n"
			+ "    a.maingroup,\r\n"
			+ "    a.subgroup,\r\n"
			+ "    a.subgroupcode,\r\n"
			+ "    a.accountcode,\r\n"
			+ "    a.accountname,\r\n"
			+ "    a.natureofaccount")
	Set<Object[]> getELActualDetails(Long orgId, String clientCode, String finyear, String previousYear, String month,
			String mainGroupName, String subGroupCode);

	@Query(nativeQuery = true,value = "select a.* from budget a where a.orgid=?1 and a.clientcode=?2 and a.year=?3 and a.maingroup=?4 and a.subgroup=?5")
	List<BudgetVO> getClientBudgetDls(Long orgId, String clientCode, String year, String mainGroup, String subGroup);


	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?4\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    acc.accountcode,\r\n"
			+ "    acc.accountname,\r\n"
			+ "    m.month,\r\n"
			+ "    SUM(b.amount) AS total_amount\r\n"
			+ "FROM Months m\r\n"
			+ "CROSS JOIN Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN budget b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname=j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "GROUP BY acc.accountname, acc.accountcode, m.month, acc.displayseq\r\n"
			+ "ORDER BY \r\n"
			+ "    CAST(acc.displayseq AS UNSIGNED),\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> getBudgetDetailsAuto(Long orgId, String finyear,  String clientCode,String mainGroupName);
	
	
	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?4\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    acc.accountcode,\r\n"
			+ "    acc.accountname,\r\n"
			+ "    m.month,\r\n"
			+ "    SUM(b.amount) AS total_amount\r\n"
			+ "FROM Months m\r\n"
			+ "CROSS JOIN Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname=j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "GROUP BY acc.accountname, acc.accountcode, m.month, acc.displayseq\r\n"
			+ "ORDER BY \r\n"
			+ "    CAST(acc.displayseq AS UNSIGNED),\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> getPYDetailsAuto(Long orgId, String finyear,  String clientCode,String mainGroupName);

	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month, 1 AS month_order UNION ALL\r\n"
			+ "    SELECT 'May', 2 UNION ALL\r\n"
			+ "    SELECT 'June', 3 UNION ALL\r\n"
			+ "    SELECT 'July', 4 UNION ALL\r\n"
			+ "    SELECT 'August', 5 UNION ALL\r\n"
			+ "    SELECT 'September', 6 UNION ALL\r\n"
			+ "    SELECT 'October', 7 UNION ALL\r\n"
			+ "    SELECT 'November', 8 UNION ALL\r\n"
			+ "    SELECT 'December', 9 UNION ALL\r\n"
			+ "    SELECT 'January', 10 UNION ALL\r\n"
			+ "    SELECT 'February', 11 UNION ALL\r\n"
			+ "    SELECT 'March', 12\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?4\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ "),\r\n"
			+ "ClosingStock AS (\r\n"
			+ "    SELECT \r\n"
			+ "        b.month,\r\n"
			+ "        b.amount,\r\n"
			+ "        b.year,\r\n"
			+ "        ROW_NUMBER() OVER (\r\n"
			+ "            ORDER BY \r\n"
			+ "                FIELD(b.month, 'April', 'May', 'June', 'July', 'August', 'September', \r\n"
			+ "                             'October', 'November', 'December', 'January', 'February', 'March')\r\n"
			+ "        ) AS rn\r\n"
			+ "    FROM automation h \r\n"
			+ "    JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "    JOIN budget b ON j.accountname = b.accountname\r\n"
			+ "        AND j.maingroup = b.maingroup\r\n"
			+ "        AND j.subgroup = b.subgroup\r\n"
			+ "        AND h.subheading = 'Closing Stock'\r\n"
			+ "    WHERE b.year IN (?2, ?6)\r\n"
			+ "      AND b.orgid = ?1\r\n"
			+ "      AND b.clientcode = ?3\r\n"
			+ "),\r\n"
			+ "OpeningStockAdjustment AS (\r\n"
			+ "    SELECT \r\n"
			+ "        m.month,\r\n"
			+ "        cs.amount AS opening_stock_amount\r\n"
			+ "    FROM Months m\r\n"
			+ "    LEFT JOIN (\r\n"
			+ "        SELECT \r\n"
			+ "            b.month,\r\n"
			+ "            b.amount,\r\n"
			+ "            b.year\r\n"
			+ "        FROM automation h \r\n"
			+ "        JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "        JOIN budget b ON j.accountname = b.accountname\r\n"
			+ "            AND j.maingroup = b.maingroup\r\n"
			+ "            AND j.subgroup = b.subgroup\r\n"
			+ "            AND h.subheading = 'Closing Stock'\r\n"
			+ "        WHERE b.year IN (?2, ?6)\r\n"
			+ "          AND b.orgid = ?1\r\n"
			+ "          AND b.clientcode = ?3\r\n"
			+ "    ) cs ON \r\n"
			+ "        (\r\n"
			+ "            -- For FY: April's opening = previous year's March\r\n"
			+ "            (?5 = 'FY' AND m.month = 'April' AND cs.month = 'March' AND cs.year = ?6) \r\n"
			+ "        ) OR (\r\n"
			+ "            -- For CY: January's opening = previous year's December\r\n"
			+ "            (?5 = 'CY' AND m.month = 'January' AND cs.month = 'December' AND cs.year = ?6) \r\n"
			+ "        )OR (\r\n"
			+ "            -- For CY: January's opening = previous year's December\r\n"
			+ "            (?5 = 'CY' AND m.month = 'April' AND cs.month = 'March' AND cs.year = ?2) \r\n"
			+ "        )OR (\r\n"
			+ "            -- For CY: January's opening = previous year's December\r\n"
			+ "            (?5 = 'FY' AND m.month = 'January' AND cs.month = 'December' AND cs.year = ?2) \r\n"
			+ "        ) OR (\r\n"
			+ "            -- Other months: opening = previous month in current year\r\n"
			+ "            (\r\n"
			+ "                (m.month = 'May' AND cs.month = 'April') OR\r\n"
			+ "                (m.month = 'June' AND cs.month = 'May') OR\r\n"
			+ "                (m.month = 'July' AND cs.month = 'June') OR\r\n"
			+ "                (m.month = 'August' AND cs.month = 'July') OR\r\n"
			+ "                (m.month = 'September' AND cs.month = 'August') OR\r\n"
			+ "                (m.month = 'October' AND cs.month = 'September') OR\r\n"
			+ "                (m.month = 'November' AND cs.month = 'October') OR\r\n"
			+ "                (m.month = 'December' AND cs.month = 'November') OR\r\n"
			+ "                (m.month = 'February' AND cs.month = 'January') OR\r\n"
			+ "                (m.month = 'March' AND cs.month = 'February')\r\n"
			+ "            )\r\n"
			+ "            AND cs.year = ?2\r\n"
			+ "        )\r\n"
			+ ")\r\n"
			+ "\r\n"
			+ "SELECT \r\n"
			+ "    acc.accountcode,\r\n"
			+ "    acc.accountname,\r\n"
			+ "    m.month,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN acc.accountname = 'Opening Stock' THEN osa.opening_stock_amount\r\n"
			+ "        ELSE SUM(b.amount)\r\n"
			+ "    END AS total_amount\r\n"
			+ "FROM Months m\r\n"
			+ "CROSS JOIN Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN budget b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "LEFT JOIN OpeningStockAdjustment osa ON acc.accountname = 'Opening Stock' AND m.month = osa.month\r\n"
			+ "GROUP BY acc.accountname, acc.accountcode, m.month, acc.displayseq, osa.opening_stock_amount, m.month_order\r\n"
			+ "ORDER BY \r\n"
			+ "    CAST(acc.displayseq AS UNSIGNED),\r\n"
			+ "    m.month_order")
	Set<Object[]> getProfitAndLossBudgetDetailsAuto(Long orgId, String year, String clientCode, String mainGroup,
			String clientYear, String previousYear);
	
	

}
