package com.ebooks.elevate.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.transaction.annotation.Transactional;

import com.ebooks.elevate.entity.PreviousYearActualVO;

public interface PreviousYearActualRepo extends JpaRepository<PreviousYearActualVO, Long>{

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    ROW_NUMBER() OVER (ORDER BY accountcode) AS `ELGLS.No`,\r\n"
			+ "    accountname AS `ELGL`,\r\n"
			+ "    accountcode AS `ELGLCode`,\r\n"
			+ "    natureofaccount AS `NLDN/CR`,\r\n"
			+ "    MAX(CASE WHEN month = 'January' THEN amount ELSE 0 END) AS 'January',\r\n"
			+ "    MAX(CASE WHEN month = 'February' THEN amount ELSE 0 END) AS 'February',\r\n"
			+ "    MAX(CASE WHEN month = 'March' THEN amount ELSE 0 END) AS 'March',\r\n"
			+ "    MAX(CASE WHEN month = 'April' THEN amount ELSE 0 END) AS 'April',\r\n"
			+ "    MAX(CASE WHEN month = 'May' THEN amount ELSE 0 END) AS 'May',\r\n"
			+ "    MAX(CASE WHEN month = 'June' THEN amount ELSE 0 END) AS 'June',\r\n"
			+ "    MAX(CASE WHEN month = 'July' THEN amount ELSE 0 END) AS 'July',\r\n"
			+ "    MAX(CASE WHEN month = 'August' THEN amount ELSE 0 END) AS 'August',\r\n"
			+ "    MAX(CASE WHEN month = 'September' THEN amount ELSE 0 END) AS 'September',\r\n"
			+ "    MAX(CASE WHEN month = 'October' THEN amount ELSE 0 END) AS 'October',\r\n"
			+ "    MAX(CASE WHEN month = 'November' THEN amount ELSE 0 END) AS 'November',\r\n"
			+ "    MAX(CASE WHEN month = 'December' THEN amount ELSE 0 END) AS 'December'\r\n"
			+ "FROM previousyearactual where year=?2 and orgid=?1 and client=?3 and clientcode=?4 \r\n"
			+ "GROUP BY accountname, accountcode, natureofaccount\r\n"
			+ "ORDER BY accountcode")
	Set<Object[]> getClientPreviousYearActualDetails(Long orgId, String year, String client, String clientCode);

	@Query(nativeQuery = true,value = "select * from previousyearactual where orgid=?1 and clientcode=?2 and year=?3 and month=?4 and maingroup=?5 and subgroupcode=?6 and accountcode=?7")
	List<PreviousYearActualVO> getPreviousYearDetails1(Long orgId, String clientCode, String year, String month,
			String mainGroup, String subGroupCode, String accountCode);

	@Query(nativeQuery = true,value = "SELECT \r\n"
			+ "    a.maingroup, \r\n"
			+ "    a.subgroup, \r\n"
			+ "    a.subgroupcode, \r\n"
			+ "    a.accountcode, \r\n"
			+ "    a.accountname,\r\n"
			+ "    a.natureofaccount, \r\n"
			+ "    a.quater, \r\n"
			+ "    SUM(a.previousYear) AS previousYear,gl.displayseq\r\n"
			+ "FROM (\r\n"
			+ "    SELECT \r\n"
			+ "        maingroup, \r\n"
			+ "        subgroup, \r\n"
			+ "        subgroupcode, \r\n"
			+ "        accountcode, \r\n"
			+ "        accountname, \r\n"
			+ "        natureofaccount, \r\n"
			+ "        quater,\r\n"
			+ "        SUM(amount) AS previousYear\r\n"
			+ "    FROM previousyearactual\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "    GROUP BY \r\n"
			+ "        maingroup, \r\n"
			+ "        subgroup, \r\n"
			+ "        natureofaccount, \r\n"
			+ "        subgroupcode, \r\n"
			+ "        accountcode, \r\n"
			+ "        accountname, \r\n"
			+ "        quater\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT \r\n"
			+ "        maingroup, \r\n"
			+ "        subgroup, \r\n"
			+ "        subgroupcode, \r\n"
			+ "        accountcode, \r\n"
			+ "        accountname, \r\n"
			+ "        natureofaccount, \r\n"
			+ "        'YTD' AS quater,\r\n"
			+ "        SUM(amount) AS previousYear\r\n"
			+ "    FROM previousyearactual\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND monthsequence <= (\r\n"
			+ "          SELECT MAX(monthsequence)\r\n"
			+ "          FROM previousyearactual\r\n"
			+ "          WHERE year = ?2\r\n"
			+ "            AND month = ?6\r\n"
			+ "            AND clientcode = ?3\r\n"
			+ "      )\r\n"
			+ "    GROUP BY \r\n"
			+ "        maingroup, \r\n"
			+ "        subgroup, \r\n"
			+ "        natureofaccount, \r\n"
			+ "        subgroupcode, \r\n"
			+ "        accountcode, \r\n"
			+ "        accountname\r\n"
			+ ") AS a JOIN groupledgers gl ON a.accountname = gl.accountname and gl.groupname=?4 and \r\n"
			+ " a.maingroup = ?4 \r\n"
			+ "  AND  (a.subgroup=?5 or 'ALL'=?5)\r\n"
			+ "GROUP BY \r\n"
			+ "    a.maingroup, \r\n"
			+ "    a.subgroup, \r\n"
			+ "    a.subgroupcode, \r\n"
			+ "    a.accountcode, \r\n"
			+ "    a.accountname, \r\n"
			+ "    a.natureofaccount, \r\n"
			+ "    a.quater,gl.displayseq ORDER BY cast(gl.displayseq as unsigned)")
	Set<Object[]> getELPYDetails(Long orgId, String finyear, String clientCode, String mainGroupName,
			String subGroupCode,String month);
	
	
	
//	@Query(nativeQuery = true,value = "SELECT \r\n"
//			+ "    a.maingroup,\r\n"
//			+ "    a.subgroup,\r\n"
//			+ "    a.subgroupcode,\r\n"
//			+ "    a.accountcode,\r\n"
//			+ "    a.accountname,\r\n"
//			+ "    a.natureofaccount,\r\n"
//			+ "    quater,\r\n"
//			+ "    SUM(a.budget) AS budget,\r\n"
//			+ "    SUM(a.actual) AS actual,\r\n"
//			+ "    SUM(a.PY) AS PY\r\n"
//			+ "FROM (\r\n"
//			+ "    SELECT \r\n"
//			+ "        maingroup,\r\n"
//			+ "        subgroup,\r\n"
//			+ "        subgroupcode,\r\n"
//			+ "        accountcode,\r\n"
//			+ "        accountname,\r\n"
//			+ "        natureofaccount,\r\n"
//			+ "        quater,\r\n"
//			+ "        SUM(truncate(amount/?8,2)*?8) AS budget,\r\n"
//			+ "        0 AS actual,\r\n"
//			+ "        0 AS PY\r\n"
//			+ "    FROM budget \r\n"
//			+ "    WHERE orgid = ?1\r\n"
//			+ "      AND clientcode = ?2 \r\n"
//			+ "      AND year = ?3 \r\n"
//			+ "      and monthsequence <=(select distinct monthsequence from budget where  orgid = ?1\r\n"
//			+ "      AND clientcode = ?2 \r\n"
//			+ "      AND year = ?3 \r\n"
//			+ "      AND month = ?5)\r\n"
//			+ "    GROUP BY maingroup, subgroup, subgroupcode, accountcode, natureofaccount, accountname, quater\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    SELECT \r\n"
//			+ "        maingroup,\r\n"
//			+ "        subgroup,\r\n"
//			+ "        subgroupcode,\r\n"
//			+ "        accountcode,\r\n"
//			+ "        accountname,\r\n"
//			+ "        natureofaccount,\r\n"
//			+ "        quater,\r\n"
//			+ "        0 AS budget,\r\n"
//			+ "        SUM(truncate(amount/?8,2)*?8) AS actual,\r\n"
//			+ "        0 AS PY\r\n"
//			+ "    FROM previousyearactual \r\n"
//			+ "    WHERE orgid = ?1\r\n"
//			+ "      AND clientcode = ?2 \r\n"
//			+ "      AND year = ?3 \r\n"
//			+ "      and monthsequence <=(select distinct monthsequence from previousyearactual where  orgid = ?1\r\n"
//			+ "      AND clientcode = ?2 \r\n"
//			+ "      AND year = ?3 \r\n"
//			+ "      AND month = ?5)\r\n"
//			+ "    GROUP BY maingroup, subgroup, natureofaccount, subgroupcode, accountcode, accountname, quater\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    SELECT \r\n"
//			+ "        maingroup,\r\n"
//			+ "        subgroup,\r\n"
//			+ "        subgroupcode,\r\n"
//			+ "        accountcode,\r\n"
//			+ "        accountname,\r\n"
//			+ "        natureofaccount,\r\n"
//			+ "        quater,\r\n"
//			+ "        0 AS budget,\r\n"
//			+ "        0 AS actual,\r\n"
//			+ "        SUM(truncate(amount/?8,2)*?8) AS PY\r\n"
//			+ "    FROM previousyearactual \r\n"
//			+ "    WHERE orgid = ?1\r\n"
//			+ "      AND clientcode = ?2 \r\n"
//			+ "      AND year = ?4 \r\n"
//			+ "      and monthsequence <=(select distinct monthsequence from previousyearactual where  orgid = ?1\r\n"
//			+ "      AND clientcode = ?2 \r\n"
//			+ "      AND year = ?4 \r\n"
//			+ "      AND month = ?5)\r\n"
//			+ "    GROUP BY maingroup, subgroup, natureofaccount, subgroupcode, accountcode, accountname, quater\r\n"
//			+ ") a\r\n"
//			+ "JOIN groupledgers gl \r\n"
//			+ "    ON a.accountname = gl.accountname \r\n"
//			+ "    AND gl.groupname = ?6\r\n"
//			+ "    AND a.maingroup = ?6 \r\n"
//			+ "    AND (a.subgroup = ?7 OR ?7 = 'ALL')\r\n"
//			+ "GROUP BY \r\n"
//			+ "    a.maingroup,\r\n"
//			+ "    a.subgroup,\r\n"
//			+ "    a.subgroupcode,\r\n"
//			+ "    a.accountcode,\r\n"
//			+ "    a.accountname,\r\n"
//			+ "    a.natureofaccount,\r\n"
//			+ "    quater,gl.displayseq\r\n"
//			+ "ORDER BY CAST(gl.displayseq AS UNSIGNED)")
//	Set<Object[]> getELActualQuaterDetails(Long orgId, String clientCode, String finyear, String previousYear, String month,
//			String mainGroupName, String subGroupCode,int finDevideAmount);
	
	@Query(nativeQuery = true, value = "WITH curr_month AS (\r\n"
			+ "			    SELECT t.monthsequence\r\n"
			+ "			    FROM budget t\r\n"
			+ "			    WHERE t.orgid = ?1\r\n"
			+ "			      AND t.clientcode = ?2\r\n"
			+ "			      AND t.year = ?3\r\n"
			+ "			      AND t.month = ?5\r\n"
			+ "			    LIMIT 1\r\n"
			+ "			),\r\n"
			+ "			\r\n"
			+ "			latest_quarter_month AS (\r\n"
			+ "			    SELECT\r\n"
			+ "			        b.orgid,\r\n"
			+ "			        b.clientcode,\r\n"
			+ "			        b.year,\r\n"
			+ "			        b.maingroup,\r\n"
			+ "			        b.accountcode,\r\n"
			+ "			        b.quater,\r\n"
			+ "			        MAX(b.monthsequence) AS max_monthsequence\r\n"
			+ "			    FROM previousyearactual b\r\n"
			+ "			    JOIN curr_month cm\r\n"
			+ "			      ON b.monthsequence <= cm.monthsequence\r\n"
			+ "			    GROUP BY\r\n"
			+ "			        b.orgid,\r\n"
			+ "			        b.clientcode,\r\n"
			+ "			        b.year,\r\n"
			+ "			        b.maingroup,\r\n"
			+ "			        b.accountcode,\r\n"
			+ "			        b.quater\r\n"
			+ "			),\r\n"
			+ "			\r\n"
			+ "			final_data AS (\r\n"
			+ "			\r\n"
			+ "			    /* =======================\r\n"
			+ "			       BUDGET\r\n"
			+ "			    ======================= */\r\n"
			+ "			    SELECT\r\n"
			+ "			        b.maingroup,\r\n"
			+ "			        b.subgroup,\r\n"
			+ "			        b.subgroupcode,\r\n"
			+ "			        b.accountcode,\r\n"
			+ "			        b.accountname,\r\n"
			+ "			        b.natureofaccount,\r\n"
			+ "			        b.quater,\r\n"
			+ "			\r\n"
			+ "			        CASE\r\n"
			+ "			            WHEN b.maingroup IN ('Opening Stock','Closing Stock','Balance Sheet Schedule')\r\n"
			+ "			                 AND b.monthsequence = lqm.max_monthsequence\r\n"
			+ "			            THEN TRUNCATE(b.amount / ?8, 2) * ?8\r\n"
			+ "			\r\n"
			+ "			            WHEN b.maingroup NOT IN ('Opening Stock','Closing Stock','Balance Sheet Schedule')\r\n"
			+ "			            THEN TRUNCATE(b.amount / ?8, 2) * ?8\r\n"
			+ "			\r\n"
			+ "			            ELSE 0\r\n"
			+ "			        END AS budget,\r\n"
			+ "			\r\n"
			+ "			        0 AS actual,\r\n"
			+ "			        0 AS PY\r\n"
			+ "			\r\n"
			+ "			    FROM budget b\r\n"
			+ "			    JOIN curr_month cm\r\n"
			+ "			    LEFT JOIN latest_quarter_month lqm\r\n"
			+ "			        ON lqm.orgid = b.orgid\r\n"
			+ "			       AND lqm.clientcode = b.clientcode\r\n"
			+ "			       AND lqm.year = b.year\r\n"
			+ "			       AND lqm.maingroup = b.maingroup\r\n"
			+ "			       AND lqm.accountcode = b.accountcode\r\n"
			+ "			       AND lqm.quater = b.quater\r\n"
			+ "			\r\n"
			+ "			    WHERE b.orgid = ?1\r\n"
			+ "			      AND b.clientcode = ?2\r\n"
			+ "			      AND b.year = ?3\r\n"
			+ "			      AND b.monthsequence <= cm.monthsequence\r\n"
			+ "			      AND b.maingroup = ?6 AND (b.subgroup = ?7 OR ?7 = 'ALL')\r\n"
			+ "			\r\n"
			+ "			    UNION ALL\r\n"
			+ "			\r\n"
			+ "			    /* =======================\r\n"
			+ "			       ACTUAL\r\n"
			+ "			    ======================= */\r\n"
			+ "			    SELECT\r\n"
			+ "			        a.maingroup,\r\n"
			+ "			        a.subgroup,\r\n"
			+ "			        a.subgroupcode,\r\n"
			+ "			        a.accountcode,\r\n"
			+ "			        a.accountname,\r\n"
			+ "			        a.natureofaccount,\r\n"
			+ "			        a.quater,\r\n"
			+ "			\r\n"
			+ "			        0 AS budget,\r\n"
			+ "			\r\n"
			+ "			        CASE\r\n"
			+ "			            WHEN a.maingroup IN ('Opening Stock','Closing Stock','Balance Sheet Schedule')\r\n"
			+ "			                 AND a.monthsequence = lqm.max_monthsequence\r\n"
			+ "			            THEN TRUNCATE(a.amount / ?8, 2) * ?8\r\n"
			+ "			\r\n"
			+ "			            WHEN a.maingroup NOT IN ('Opening Stock','Closing Stock','Balance Sheet Schedule')\r\n"
			+ "			            THEN TRUNCATE(a.amount / ?8, 2) * ?8\r\n"
			+ "			\r\n"
			+ "			            ELSE 0\r\n"
			+ "			        END AS actual,\r\n"
			+ "			\r\n"
			+ "			        0 AS PY\r\n"
			+ "			\r\n"
			+ "			    FROM previousyearactual a\r\n"
			+ "			    JOIN curr_month cm\r\n"
			+ "			    LEFT JOIN latest_quarter_month lqm\r\n"
			+ "			        ON lqm.orgid = a.orgid\r\n"
			+ "			       AND lqm.clientcode = a.clientcode\r\n"
			+ "			       AND lqm.year = a.year\r\n"
			+ "			       AND lqm.maingroup = a.maingroup\r\n"
			+ "			       AND lqm.accountcode = a.accountcode\r\n"
			+ "			       AND lqm.quater = a.quater\r\n"
			+ "			\r\n"
			+ "			    WHERE a.orgid = ?1\r\n"
			+ "			      AND a.clientcode = ?2\r\n"
			+ "			      AND a.year = ?3\r\n"
			+ "			      AND a.monthsequence <= cm.monthsequence\r\n"
			+ "			      AND a.maingroup = ?6 AND (a.subgroup = ?7 OR ?7 = 'ALL')\r\n"
			+ "			\r\n"
			+ "			    UNION ALL\r\n"
			+ "			\r\n"
			+ "		    /* =======================\r\n"
			+ "		       PY (Previous Year)\r\n"
			+ "		    ======================= */\r\n"
			+ "		    SELECT\r\n"
			+ "		        a.maingroup,\r\n"
			+ "		        a.subgroup,\r\n"
			+ "		        a.subgroupcode,\r\n"
			+ "		        a.accountcode,\r\n"
			+ "		        a.accountname,\r\n"
			+ "		        a.natureofaccount,\r\n"
			+ "		        a.quater,\r\n"
			+ "		\r\n"
			+ "		        0 AS budget,\r\n"
			+ "		0 as actual,\r\n"
			+ "		        CASE\r\n"
			+ "		            WHEN a.maingroup IN ('Opening Stock','Closing Stock','Balance Sheet Schedule')\r\n"
			+ "		                 AND a.monthsequence = lqm.max_monthsequence\r\n"
			+ "		            THEN TRUNCATE(a.amount / ?8, 2) * ?8\r\n"
			+ "		\r\n"
			+ "		            WHEN a.maingroup NOT IN ('Opening Stock','Closing Stock','Balance Sheet Schedule')\r\n"
			+ "		            THEN TRUNCATE(a.amount / ?8, 2) * ?8\r\n"
			+ "		\r\n"
			+ "		            ELSE 0\r\n"
			+ "		        END AS PY\r\n"
			+ "		\r\n"
			+ "		    FROM previousyearactual a\r\n"
			+ "		    JOIN curr_month cm\r\n"
			+ "		    LEFT JOIN latest_quarter_month lqm\r\n"
			+ "		        ON lqm.orgid = a.orgid\r\n"
			+ "		       AND lqm.clientcode = a.clientcode\r\n"
			+ "		       AND lqm.year = a.year\r\n"
			+ "		       AND lqm.maingroup = a.maingroup\r\n"
			+ "		       AND lqm.accountcode = a.accountcode\r\n"
			+ "		       AND lqm.quater = a.quater\r\n"
			+ "		\r\n"
			+ "		    WHERE a.orgid = ?1\r\n"
			+ "		      AND a.clientcode = ?2\r\n"
			+ "		      AND a.year = ?4\r\n"
			+ "		      AND a.monthsequence <= cm.monthsequence\r\n"
			+ "		      AND a.maingroup = ?6 AND (a.subgroup = ?7 OR ?7 = 'ALL')\r\n"
			+ "		)\r\n"
			+ "		\r\n"
			+ "		SELECT\r\n"
			+ "		    f.maingroup,\r\n"
			+ "		    f.subgroup,\r\n"
			+ "		    f.subgroupcode,\r\n"
			+ "		    f.accountcode,\r\n"
			+ "		    f.accountname,\r\n"
			+ "		    f.natureofaccount,\r\n"
			+ "		    f.quater,\r\n"
			+ "		\r\n"
			+ "		    SUM(f.budget) AS budget,\r\n"
			+ "		    SUM(f.actual) AS actual,\r\n"
			+ "		    SUM(f.PY) AS PY\r\n"
			+ "		\r\n"
			+ "		FROM final_data f\r\n"
			+ "		JOIN groupledgers gl\r\n"
			+ "		  ON f.accountname = gl.accountname\r\n"
			+ "		 AND gl.groupname = ?6 AND (gl.subgroupname = ?7 OR ?7 = 'ALL')\r\n"
			+ "		GROUP BY\r\n"
			+ "		    f.maingroup,\r\n"
			+ "		    f.subgroup,\r\n"
			+ "		    f.subgroupcode,\r\n"
			+ "		    f.accountcode,\r\n"
			+ "		    f.accountname,\r\n"
			+ "		    f.natureofaccount,\r\n"
			+ "		    f.quater,\r\n"
			+ "		    gl.displayseq\r\n"
			+ "		ORDER BY CAST(gl.displayseq AS UNSIGNED)")
	Set<Object[]> getELActualQuaterDetails(Long orgId, String clientCode, String finyear, String previousYear, String month,
			String mainGroupName, String subGroupCode,int finDevideAmount);
	
	
	@Query(nativeQuery = true,value = "select * from previousyearactual where orgid=?1 and clientcode=?2 and year=?3 and month=?4 and maingroup=?5 and subgroupcode=?6 and accountcode=?7 ")
	PreviousYearActualVO getPreviousYearDetails(Long orgId, String clientCode, String year, String month,
			String mainGroup, String subGroupCode, String accountCode);

	@Query(nativeQuery = true,value = "select a.* from previousyearactual a where a.orgid=?1 and a.clientcode=?2 and a.year=?3 and a.maingroup=?4 and a.subgroup=?5 ")
	List<PreviousYearActualVO> getClientBudgetDls(Long org, String clientcode, String yr, String maingroup,
			String subgroup);
	
	@Modifying
	@Transactional
	@Query(value = "delete from previousyearactual a where a.orgid = ?1 and a.clientcode = ?2 and a.year = ?3 and a.maingroup = ?4 and a.subgroup = ?5", nativeQuery = true)
	void deleteClientBudgetDls(Long orgId, String clientCode, String year, String mainGroup, String subGroup);

	@Query(nativeQuery = true,value = "SELECT p.month, SUM(p.amount) FROM previousyearactual p \r\n"
			+ "		       WHERE p.orgid = ?1 AND p.clientcode = ?2 AND p.year = ?3 \r\n"
			+ "		       AND p.maingroup = 'Closing Stock' GROUP BY p.month")
	List<Object[]> getMonthWiseSumAmountForClosingStock(Long orgId, String clientcode, String yr);

	@Query(nativeQuery = true, value = "select * from previousyearactual where orgid=?1 and clientcode=?2 and year=?3 and maingroup=?4 and subgroup=?5")
	List<PreviousYearActualVO> findStockDetails(Long org, String clientcode, String yr, String mGroup, String subGroup);

	@Query(nativeQuery = true,value ="SELECT p.month, SUM(p.amount) FROM previousyearactual p " +
		       "WHERE p.orgId = ?1 AND p.clientCode = ?2 AND p.year = ?3 " +
		       "AND p.mainGroup = 'Closing Stock' AND p.accountCode IN (?4) "+
		       "GROUP BY p.month")
	List<Object[]> getDrawingPowerMonthWiseSum(Long org, String clientcode, String yr, List<String> accountCodeList);

	@Query(nativeQuery = true,value ="SELECT p.month, SUM(p.amount) FROM previousyearactual p " +
		       "WHERE p.orgId = ?1 AND p.clientCode = ?2 AND p.year = ?3 " +
		       "AND p.mainGroup = 'Closing Stock' AND p.accountCode = '4009' " +
		       "GROUP BY p.month")
	List<Object[]> getMonthWiseSumForWIP(Long org, String clientcode, String yr);

	@Query(nativeQuery = true,value ="SELECT p.month, SUM(p.amount) FROM previousyearactual p " +
		       "WHERE p.orgId = ?1 AND p.clientCode = ?2 AND p.year = ?3 " +
		       "AND p.mainGroup = 'Closing Stock' AND p.accountCode IN (?4) "+
		       "GROUP BY p.month")
	List<Object[]> getMonthWiseSumForFinishedGoods(Long org, String clientcode, String yr,
			List<String> finishedGoodsCodes);
	
	@Query(nativeQuery = true, value = "select * from previousyearactual where orgid=?1 and clientcode=?2 and year=?3 and maingroup=?4 and subgroup=?5 and accountname=?6 ")
	List<PreviousYearActualVO> findOldDetails(Long orgId, String clientCode, String year, String mg, String mg2, String raw);

	@Modifying
    @Transactional
    @Query(value = "DELETE FROM previousyearactual " +
                   "WHERE orgid = ?1 " +
                   "AND clientcode = ?2 " +
                   "AND year = ?3 " +
                   "AND maingroup = ?4 " +
                   "AND subgroup = ?5 " +
                   "AND month = ?6", nativeQuery = true)
	void deleteByOrgIdAndClientAndYearAndMainGroupAndSubGroupAndMonth(Long orgId, String clientCode, String year,
			String mainGroup, String subGroup, String month);

//	@Query(nativeQuery = true, value = "WITH params AS (\r\n"
//			+ "    SELECT \r\n"
//			+ "        ?1 AS orgid,\r\n"
//			+ "        ?3 AS currentFinYear,\r\n"
//			+ "        ?4 AS previousFinYear,\r\n"
//			+ "        ?2 AS client,\r\n"
//			+ "        ?6 AS maingroup,\r\n"
//			+ "        ?5 AS currentMonth\r\n"
//			+ "),\r\n"
//			+ "Accounts AS (\r\n"
//			+ "    SELECT \r\n"
//			+ "        a.displayseq, \r\n"
//			+ "        a.accountname,\r\n"
//			+ "        a.accountcode,\r\n"
//			+ "        a.subgroupname,\r\n"
//			+ "        a.subgroupcode\r\n"
//			+ "    FROM groupledgers a\r\n"
//			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
//			+ "    JOIN params p\r\n"
//			+ "    WHERE b.groupname = p.maingroup\r\n"
//			+ "      AND a.active = 1\r\n"
//			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
//			+ "),\r\n"
//			+ "budget_data AS (\r\n"
//			+ "    SELECT\r\n"
//			+ "        b.accountcode,\r\n"
//			+ "        b.accountname,\r\n"
//			+ "        m.monthsequence,\r\n"
//			+ "        b.month,\r\n"
//			+ "        b.year,\r\n"
//			+ "        b.budgetamount AS budget,\r\n"
//			+ "        b.actualamount AS actual,\r\n"
//			+ "        b.pyamount AS PY,b.quater\r\n"
//			+ "    FROM budget b \r\n"
//			+ "    JOIN params p\r\n"
//			+ "      ON b.orgid = p.orgid AND b.month = ?5\r\n"
//			+ "     AND b.client = p.client\r\n"
//			+ "     AND b.maingroup = p.maingroup\r\n"
//			+ "     AND b.year IN (p.currentFinYear, p.previousFinYear)\r\n"
//			+ ")\r\n"
//			+ "SELECT\r\n"
//			+ "h.accountcode,\r\n"
//			+ "    h.accountname,\r\n"
//			+ "    ROUND(SUM(h.budget), 2) AS budget,\r\n"
//			+ "    ROUND(SUM(h.actual), 2) AS actual,\r\n"
//			+ "    ROUND(SUM(h.PY), 2) AS PY,h.quater,h.display_sequence\r\n"
//			+ "FROM (\r\n"
//			+ "    -- budget\r\n"
//			+ "    SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
//			+ "           b.natureofaccount,\r\n"
//			+ "           case when h.maingroupname = 'Balance Sheet' THEN \r\n"
//			+ "           b.amount else  SUM(b.amount)  end budget,\r\n"
//			+ "           0 actual, 0 PY,  acc.displayseq AS display_sequence,b.quater\r\n"
//			+ "    FROM Accounts acc\r\n"
//			+ "    LEFT JOIN automation h ON h.maingroupname =  ?6\r\n"
//			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
//			+ "    LEFT JOIN budget b \r\n"
//			+ "        ON acc.accountname = h.subheading\r\n"
//			+ "        AND b.accountname = j.accountname\r\n"
//			+ "        AND j.accountname = b.accountname\r\n"
//			+ "        AND j.maingroup = b.maingroup\r\n"
//			+ "        AND j.subgroup = b.subgroup\r\n"
//			+ "        AND b.year = ?3\r\n"
//			+ "        AND b.orgid = ?1\r\n"
//			+ "        AND b.clientcode = ?2\r\n"
//			+ "AND (\r\n"
//			+ "    (\r\n"
//			+ "        -- 🧾 For Balance Sheet: Only current quarter-end month\r\n"
//			+ "        h.maingroupname = 'Balance Sheet'\r\n"
//			+ "        AND b.year = ?3\r\n"
//			+ "        AND b.monthsequence <= (\r\n"
//			+ "            SELECT monthsequence \r\n"
//			+ "            FROM budget \r\n"
//			+ "            WHERE year = ?3 \r\n"
//			+ "              AND month = ?5 \r\n"
//			+ "            GROUP BY monthsequence\r\n"
//			+ "        )\r\n"
//			+ "        AND (\r\n"
//			+ "            b.monthsequence % 3 = 0  -- last month of quarter (e.g. June, Sept, Dec, Mar)\r\n"
//			+ "            OR b.month = ?5    -- or explicitly current month if mid-quarter\r\n"
//			+ "        )\r\n"
//			+ "    )\r\n"
//			+ "    OR (\r\n"
//			+ "        -- 📊 For Profit & Loss: All months up to current\r\n"
//			+ "        h.maingroupname <> 'Balance Sheet'\r\n"
//			+ "        AND b.monthsequence <= (\r\n"
//			+ "            SELECT monthsequence \r\n"
//			+ "            FROM budget \r\n"
//			+ "            WHERE year = ?3 \r\n"
//			+ "              AND month = ?5 \r\n"
//			+ "            GROUP BY monthsequence\r\n"
//			+ "        )\r\n"
//			+ "    )\r\n"
//			+ ")\r\n"
//			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
//			+ "             b.natureofaccount, acc.displayseq,b.quater,b.amount\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    -- actual\r\n"
//			+ "    SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
//			+ "           b.natureofaccount, 0 budget, case when h.maingroupname = 'Balance Sheet' THEN \r\n"
//			+ "           b.amount else  SUM(b.amount)  end actual,\r\n"
//			+ "            0 PY,  acc.displayseq AS display_sequence,b.quater\r\n"
//			+ "    FROM Accounts acc\r\n"
//			+ "    LEFT JOIN automation h ON h.maingroupname = ?6\r\n"
//			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
//			+ "    LEFT JOIN previousyearactual b \r\n"
//			+ "        ON acc.accountname = h.subheading\r\n"
//			+ "        AND b.accountname = j.accountname\r\n"
//			+ "        AND j.accountname = b.accountname\r\n"
//			+ "        AND j.maingroup = b.maingroup\r\n"
//			+ "        AND j.subgroup = b.subgroup\r\n"
//			+ "        AND b.year = ?3\r\n"
//			+ "        AND b.orgid = ?1\r\n"
//			+ "        AND b.clientcode = ?2 AND (\r\n"
//			+ "    (\r\n"
//			+ "        -- 🧾 For Balance Sheet: Only current quarter-end month\r\n"
//			+ "        h.maingroupname = 'Balance Sheet'\r\n"
//			+ "        AND b.year = ?3\r\n"
//			+ "        AND b.monthsequence <= (\r\n"
//			+ "            SELECT monthsequence \r\n"
//			+ "            FROM previousyearactual \r\n"
//			+ "            WHERE year = ?3 \r\n"
//			+ "              AND month = ?5 \r\n"
//			+ "            GROUP BY monthsequence\r\n"
//			+ "        )\r\n"
//			+ "        AND (\r\n"
//			+ "            b.monthsequence % 3 = 0  -- last month of quarter (e.g. June, Sept, Dec, Mar)\r\n"
//			+ "            OR b.month = ?5    -- or explicitly current month if mid-quarter\r\n"
//			+ "        )\r\n"
//			+ "    )\r\n"
//			+ "    OR (\r\n"
//			+ "        -- 📊 For Profit & Loss: All months up to current\r\n"
//			+ "        h.maingroupname <> 'Balance Sheet'\r\n"
//			+ "        AND b.monthsequence <= (\r\n"
//			+ "            SELECT monthsequence \r\n"
//			+ "            FROM previousyearactual \r\n"
//			+ "            WHERE year = ?3 \r\n"
//			+ "              AND month = ?5 \r\n"
//			+ "            GROUP BY monthsequence\r\n"
//			+ "        )\r\n"
//			+ "    )\r\n"
//			+ ")\r\n"
//			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
//			+ "             b.natureofaccount, acc.displayseq,b.quater,b.amount\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    -- PY\r\n"
//			+ "    SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
//			+ "           b.natureofaccount, 0 budget, 0 actual, case when h.maingroupname = 'Balance Sheet' THEN \r\n"
//			+ "           b.amount else  SUM(b.amount)  end PY, acc.displayseq AS display_sequence,b.quater\r\n"
//			+ "    FROM Accounts acc\r\n"
//			+ "    LEFT JOIN automation h ON h.maingroupname = ?6\r\n"
//			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
//			+ "    LEFT JOIN previousyearactual b \r\n"
//			+ "        ON acc.accountname = h.subheading\r\n"
//			+ "        AND b.accountname = j.accountname\r\n"
//			+ "        AND j.accountname = b.accountname\r\n"
//			+ "        AND j.maingroup = b.maingroup\r\n"
//			+ "        AND j.subgroup = b.subgroup\r\n"
//			+ "        AND b.year = ?4\r\n"
//			+ "        AND b.orgid = ?1\r\n"
//			+ "        AND b.clientcode = ?2 AND (\r\n"
//			+ "    (\r\n"
//			+ "        -- 🧾 For Balance Sheet: Only current quarter-end month\r\n"
//			+ "        h.maingroupname = 'Balance Sheet'\r\n"
//			+ "        AND b.year = ?4\r\n"
//			+ "        AND b.monthsequence <= (\r\n"
//			+ "            SELECT monthsequence \r\n"
//			+ "            FROM previousyearactual \r\n"
//			+ "            WHERE year = ?4 \r\n"
//			+ "              AND month = ?5 \r\n"
//			+ "            GROUP BY monthsequence\r\n"
//			+ "        )\r\n"
//			+ "        AND (\r\n"
//			+ "            b.monthsequence % 3 = 0  -- last month of quarter (e.g. June, Sept, Dec, Mar)\r\n"
//			+ "            OR b.month = ?5    -- or explicitly current month if mid-quarter\r\n"
//			+ "        )\r\n"
//			+ "    )\r\n"
//			+ "    OR (\r\n"
//			+ "        -- 📊 For Profit & Loss: All months up to current\r\n"
//			+ "        h.maingroupname <> 'Balance Sheet'\r\n"
//			+ "        AND b.monthsequence <= (\r\n"
//			+ "            SELECT monthsequence \r\n"
//			+ "            FROM previousyearactual \r\n"
//			+ "            WHERE year = ?4 \r\n"
//			+ "              AND month = ?5 \r\n"
//			+ "            GROUP BY monthsequence\r\n"
//			+ "        )\r\n"
//			+ "    )\r\n"
//			+ ")\r\n"
//			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
//			+ "             b.natureofaccount, acc.displayseq,b.quater,b.amount\r\n"
//			+ ") h\r\n"
//			+ "WHERE h.accountname IS NOT NULL \r\n"
//			+ "GROUP BY h.accountcode, h.accountname,h.quater,h.display_sequence  order by h.quater,cast(h.display_sequence as unsigned) asc")
//	Set<Object[]> getELActualAutomaticQuaterDetails(Long orgId, String clientCode, String finyear, String previousYear, String month,
//			String mainGroupName);
	
	@Query(nativeQuery = true, value = "WITH params AS (\r\n"
			+ "    SELECT \r\n"
			+ "        ?1 AS orgid,\r\n"
			+ "        ?3 AS currentFinYear,\r\n"
			+ "        ?4 AS previousFinYear,\r\n"
			+ "        ?2 AS client,\r\n"
			+ "        ?6 AS maingroup,\r\n"
			+ "        ?5 AS currentMonth\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    JOIN params p\r\n"
			+ "    WHERE b.groupname = p.maingroup\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ "),\r\n"
			+ "budget_data AS (\r\n"
			+ "    SELECT\r\n"
			+ "        b.accountcode,\r\n"
			+ "        b.accountname,\r\n"
			+ "        m.monthsequence,\r\n"
			+ "        b.month,\r\n"
			+ "        b.year,\r\n"
			+ "        b.budgetamount AS budget,\r\n"
			+ "        b.actualamount AS actual,\r\n"
			+ "        b.pyamount AS PY,b.quater\r\n"
			+ "    FROM budget b \r\n"
			+ "    JOIN params p\r\n"
			+ "      ON b.orgid = p.orgid AND b.month = ?5\r\n"
			+ "     AND b.client = p.client\r\n"
			+ "     AND b.maingroup = p.maingroup\r\n"
			+ "     AND b.year IN (p.currentFinYear, p.previousFinYear)\r\n"
			+ ")\r\n"
			+ "SELECT\r\n"
			+ "    h.accountcode,\r\n"
			+ "    h.accountname,\r\n"
			+ "    ROUND(SUM(h.budget), 2) AS budget,\r\n"
			+ "    ROUND(SUM(h.actual), 2) AS actual,\r\n"
			+ "    ROUND(SUM(h.PY), 2) AS PY,h.quater,h.display_sequence\r\n"
			+ "FROM (\r\n"
			+ "    -- budget\r\n"
			+ "    SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "           b.natureofaccount,\r\n"
			+ "           case when h.maingroupname = 'Balance Sheet' THEN \r\n"
			+ "           truncate(b.amount/?7,2)*?7 else  SUM(truncate(amount/?7,2)*?7)  end budget,\r\n"
			+ "           0 actual, 0 PY,  acc.displayseq AS display_sequence,COALESCE(b.quater, q.quater) quater\r\n"
			+ "    FROM Accounts acc\r\n"
			+ "    LEFT JOIN automation h ON h.maingroupname =  ?6\r\n"
			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "    LEFT JOIN budget b \r\n"
			+ "        ON acc.accountname = h.subheading\r\n"
			+ "        AND b.accountname = j.accountname\r\n"
			+ "        AND j.accountname = b.accountname\r\n"
			+ "        AND j.maingroup = b.maingroup\r\n"
			+ "        AND j.subgroup = b.subgroup\r\n"
			+ "        AND b.year = ?3\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND b.clientcode = ?2\r\n"
			+ "AND (\r\n"
			+ "    (\r\n"
			+ "        -- 🧾 For Balance Sheet: Only current quarter-end month\r\n"
			+ "        h.maingroupname = 'Balance Sheet'\r\n"
			+ "        AND b.year = ?3\r\n"
			+ "        AND b.monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM budget \r\n"
			+ "            WHERE year = ?3 \r\n"
			+ "              AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "        AND (\r\n"
			+ "            b.monthsequence % 3 = 0  -- last month of quarter (e.g. June, Sept, Dec, Mar)\r\n"
			+ "            OR b.month = ?5    -- or explicitly current month if mid-quarter\r\n"
			+ "        )\r\n"
			+ "    )\r\n"
			+ "    OR (\r\n"
			+ "        -- 📊 For Profit & Loss: All months up to current\r\n"
			+ "        h.maingroupname <> 'Balance Sheet'\r\n"
			+ "        AND b.monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM budget \r\n"
			+ "            WHERE year = ?3 \r\n"
			+ "              AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "    )\r\n"
			+ ")CROSS JOIN (\r\n"
			+ "    SELECT 1 AS quater UNION ALL\r\n"
			+ "    SELECT 2 UNION ALL\r\n"
			+ "    SELECT 3 UNION ALL\r\n"
			+ "    SELECT 4\r\n"
			+ ") q WHERE (b.quater IS NULL OR b.quater = q.quater)\r\n"
			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "             b.natureofaccount, acc.displayseq,COALESCE(b.quater, q.quater),b.amount\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    -- actual\r\n"
			+ "    SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "           b.natureofaccount, 0 budget, case when h.maingroupname = 'Balance Sheet' THEN \r\n"
			+ "           truncate(b.amount/?7,2)*?7 else  SUM(truncate(amount/?7,2)*?7)  end actual,\r\n"
			+ "            0 PY,  acc.displayseq AS display_sequence,COALESCE(b.quater, q.quater) quater\r\n"
			+ "    FROM Accounts acc\r\n"
			+ "    LEFT JOIN automation h ON h.maingroupname = ?6\r\n"
			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "    LEFT JOIN previousyearactual b \r\n"
			+ "        ON acc.accountname = h.subheading\r\n"
			+ "        AND b.accountname = j.accountname\r\n"
			+ "        AND j.accountname = b.accountname\r\n"
			+ "        AND j.maingroup = b.maingroup\r\n"
			+ "        AND j.subgroup = b.subgroup\r\n"
			+ "        AND b.year = ?3\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND b.clientcode = ?2 AND (\r\n"
			+ "    (\r\n"
			+ "        -- 🧾 For Balance Sheet: Only current quarter-end month\r\n"
			+ "        h.maingroupname = 'Balance Sheet'\r\n"
			+ "        AND b.year = ?3\r\n"
			+ "        AND b.monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM previousyearactual \r\n"
			+ "            WHERE year = ?3 \r\n"
			+ "              AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "        AND (\r\n"
			+ "            b.monthsequence % 3 = 0  -- last month of quarter (e.g. June, Sept, Dec, Mar)\r\n"
			+ "            OR b.month = ?5    -- or explicitly current month if mid-quarter\r\n"
			+ "        )\r\n"
			+ "    )\r\n"
			+ "    OR (\r\n"
			+ "        -- 📊 For Profit & Loss: All months up to current\r\n"
			+ "        h.maingroupname <> 'Balance Sheet'\r\n"
			+ "        AND b.monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM previousyearactual \r\n"
			+ "            WHERE year = ?3 \r\n"
			+ "              AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "    )\r\n"
			+ ")CROSS JOIN (\r\n"
			+ "    SELECT 1 AS quater UNION ALL\r\n"
			+ "    SELECT 2 UNION ALL\r\n"
			+ "    SELECT 3 UNION ALL\r\n"
			+ "    SELECT 4\r\n"
			+ ") q WHERE (b.quater IS NULL OR b.quater = q.quater)\r\n"
			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "             b.natureofaccount, acc.displayseq,COALESCE(b.quater, q.quater),b.amount\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    -- PY\r\n"
			+ "    SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "           b.natureofaccount, 0 budget, 0 actual, case when h.maingroupname = 'Balance Sheet' THEN \r\n"
			+ "           truncate(b.amount/?7,2)*?7 else  SUM(truncate(amount/?7,2)*?7)  end PY, acc.displayseq AS display_sequence,COALESCE(b.quater, q.quater) quater\r\n"
			+ "    FROM Accounts acc\r\n"
			+ "    LEFT JOIN automation h ON h.maingroupname = ?6\r\n"
			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "    LEFT JOIN previousyearactual b \r\n"
			+ "        ON acc.accountname = h.subheading\r\n"
			+ "        AND b.accountname = j.accountname\r\n"
			+ "        AND j.accountname = b.accountname\r\n"
			+ "        AND j.maingroup = b.maingroup\r\n"
			+ "        AND j.subgroup = b.subgroup\r\n"
			+ "        AND b.year = ?4\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND b.clientcode = ?2 AND (\r\n"
			+ "    (\r\n"
			+ "        -- 🧾 For Balance Sheet: Only current quarter-end month\r\n"
			+ "        h.maingroupname = 'Balance Sheet'\r\n"
			+ "        AND b.year = ?4\r\n"
			+ "        AND b.monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM previousyearactual \r\n"
			+ "            WHERE year = ?4 \r\n"
			+ "              AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "        AND (\r\n"
			+ "            b.monthsequence % 3 = 0  -- last month of quarter (e.g. June, Sept, Dec, Mar)\r\n"
			+ "            OR b.month = ?5    -- or explicitly current month if mid-quarter\r\n"
			+ "        )\r\n"
			+ "    )\r\n"
			+ "    OR (\r\n"
			+ "        -- 📊 For Profit & Loss: All months up to current\r\n"
			+ "        h.maingroupname <> 'Balance Sheet'\r\n"
			+ "        AND b.monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM previousyearactual \r\n"
			+ "            WHERE year = ?4 \r\n"
			+ "              AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "    )\r\n"
			+ ")CROSS JOIN (\r\n"
			+ "    SELECT 1 AS quater UNION ALL\r\n"
			+ "    SELECT 2 UNION ALL\r\n"
			+ "    SELECT 3 UNION ALL\r\n"
			+ "    SELECT 4\r\n"
			+ ") q WHERE (b.quater IS NULL OR b.quater = q.quater)\r\n"
			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "             b.natureofaccount, acc.displayseq,COALESCE(b.quater, q.quater),b.amount\r\n"
			+ ") h\r\n"
			+ "WHERE h.accountname IS NOT NULL \r\n"
			+ "GROUP BY h.accountcode, h.accountname,h.quater,h.display_sequence  order by h.quater,cast(h.display_sequence as unsigned) asc")
	Set<Object[]> getELActualAutomaticQuaterDetails(Long orgId, String clientCode, String finyear, String previousYear, String month,
			String mainGroupName,int findevideamount);

	@Query(nativeQuery = true, value = "select * from previousyearactual where year=?1 and clientcode=?2 and month=?3 and maingroup=?4")
	List<PreviousYearActualVO> getDetails(String year, String clientCode, String month, String group);

	@Query(nativeQuery = true, value = "select row_number() over() sno,u.heading,u.maingroup,sum(u.bud)bud,sum(u.act)act,sum(u.py)py,sum(u.bud)ybud,sum(u.act)yact,sum(u.py)ypy,sum(u.bud)fbud,sum(u.act)estimate,sum(u.py)fpy from(\r\n"
			+ "select t.heading,t.maingroup,sum(t.bud)bud,sum(t.act)act,sum(t.py)py from(\r\n"
			+ "select 'Balance Sheet'heading, 'Total Capital Employed' mainGroup,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Capitals' and accountname not in('Closing Capital','Total Capital') then amount\r\n"
			+ "	when maingroup='Balance Sheet Schedule' and subgroup='Loan' and accountname not in('Total Loan')then amount else 0 end) bud,0 act,0 py\r\n"
			+ " from budget where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4 \r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Total Capital Employed' mainGroup,0 bud,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Capitals' and accountname not in('Closing Capital','Total Capital') then amount\r\n"
			+ "	when maingroup='Balance Sheet Schedule' and subgroup='Loan' and accountname not in('Total Loan')then amount else 0 end) act,0 py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4\r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Total Capital Employed' mainGroup,0 bud,0 act,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Capitals' and accountname not in('Closing Capital','Total Capital') then amount\r\n"
			+ "	when maingroup='Balance Sheet Schedule' and subgroup='Loan' and accountname not in('Total Loan')then amount else 0 end)py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?3\r\n"
			+ "  AND month = ?4) t group by t.heading,t.maingroup\r\n"
			+ "  union\r\n"
			+ "  select t.heading,t.maingroup,sum(t.bud)bud,sum(t.act)act,sum(t.py)py from(\r\n"
			+ "select 'Balance Sheet'heading, 'Fixed Assets' mainGroup,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Fixed Assets' and accountname not in('Total Fixed Assets') then amount else 0 end) bud,0 act,0 py\r\n"
			+ " from budget where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4 \r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Fixed Assets' mainGroup,0 bud,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Fixed Assets' and accountname not in('Total Fixed Assets') then amount else 0 end) act,0 py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4\r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Fixed Assets' mainGroup,0 bud,0 act,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Fixed Assets' and accountname not in('Total Fixed Assets') then amount else 0 end)py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?3\r\n"
			+ "  AND month = ?4) t group by t.heading,t.maingroup\r\n"
			+ "  union\r\n"
			+ "  select t.heading,t.maingroup,sum(t.bud)bud,sum(t.act)act,sum(t.py)py from(\r\n"
			+ "select 'Balance Sheet'heading, 'Inverstment' mainGroup,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Investment' and accountname not in('Total Investments') then amount else 0 end) bud,0 act,0 py\r\n"
			+ " from budget where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4 \r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Inverstment' mainGroup,0 bud,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Investment' and accountname not in('Total Investments') then amount else 0 end) act,0 py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4\r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Inverstment' mainGroup,0 bud,0 act,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Investment' and accountname not in('Total Investments') then amount else 0 end)py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?3\r\n"
			+ "  AND month = ?4) t group by t.heading,t.maingroup\r\n"
			+ "  union\r\n"
			+ "  select t.heading,t.maingroup,sum(t.bud)bud,sum(t.act)act,sum(t.py)py from(\r\n"
			+ "select 'Balance Sheet'heading, 'Cash And Bank Balance' mainGroup,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule' and subgroup='Cash & Bank Balance' and accountname not in('Total Cash and Bank Balance') then amount else 0 end) bud,0 act,0 py\r\n"
			+ " from budget where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4 \r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Cash And Bank Balance' mainGroup,0 bud,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule'  and subgroup='Cash & Bank Balance' and accountname not in('Total Cash and Bank Balance') then amount else 0 end) act,0 py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4\r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Cash And Bank Balance' mainGroup,0 bud,0 act,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule'  and subgroup='Cash & Bank Balance' and accountname not in('Total Cash and Bank Balance') then amount else 0 end)py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?3\r\n"
			+ "  AND month = ?4) t group by t.heading,t.maingroup\r\n"
			+ "  union\r\n"
			+ "  select t.heading,t.maingroup,sum(t.bud)bud,sum(t.act)act,sum(t.py)py from(\r\n"
			+ "select 'Balance Sheet'heading, 'Net Working Capital' mainGroup,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule'  and subgroup in('Loans And Advance','Sundry Debtors' ,'Stock') and accountname not in('Total Loan Advances','Total Sundry Debtors') then amount\r\n"
			+ " when maingroup='Balance Sheet Schedule'  and subgroup in('Sundry Creditors','Statutory Liability' ,'Other Liability') \r\n"
			+ "  and accountname not in('Total Statutory Liabilities','Total Sundry Creditors','Total Other Liabilities') then -amount else 0 end) bud,0 act,0 py\r\n"
			+ " from budget where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4 \r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Net Working Capital' mainGroup,0 bud,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule'  and subgroup in('Loans And Advance','Sundry Debtors' ,'Stock') and accountname not in('Total Loan Advances','Total Sundry Debtors') then amount\r\n"
			+ " when maingroup='Balance Sheet Schedule'  and subgroup in('Sundry Creditors','Statutory Liability' ,'Other Liability') \r\n"
			+ "  and accountname not in('Total Statutory Liabilities','Total Sundry Creditors','Total Other Liabilities') then -amount else 0 end) act,0 py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month = ?4\r\n"
			+ "  union\r\n"
			+ "  select 'Balance Sheet'heading, 'Net Working Capital' mainGroup,0 bud,0 act,sum(\r\n"
			+ "case when  maingroup='Balance Sheet Schedule'  and subgroup in('Loans And Advance','Sundry Debtors' ,'Stock') and accountname not in('Total Loan Advances','Total Sundry Debtors') then amount\r\n"
			+ " when maingroup='Balance Sheet Schedule'  and subgroup in('Sundry Creditors','Statutory Liability' ,'Other Liability') \r\n"
			+ "  and accountname not in('Total Statutory Liabilities','Total Sundry Creditors','Total Other Liabilities') then -amount else 0 end)py\r\n"
			+ " from previousyearactual where clientcode = ?1\r\n"
			+ "  AND year = ?3\r\n"
			+ "  AND month = ?4) t group by t.heading,t.maingroup)u group by u.heading,u.maingroup")
	Set<Object[]> getELSummaryBalanceSheetReport(String clientCode, String finYear, String previousYear, String month);
	
	
	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    ROW_NUMBER() OVER() AS sno,\r\n"
			+ "    t.heading,\r\n"
			+ "    t.maingroup,\r\n"
			+ "    0 AS bud,\r\n"
			+ "    0 AS act,\r\n"
			+ "    0 AS py,\r\n"
			+ "    SUM(t.bud) AS ybud,\r\n"
			+ "    SUM(t.act) AS yact,\r\n"
			+ "    SUM(t.py) AS ypy,\r\n"
			+ "    0 AS fbud,\r\n"
			+ "    0 AS estimate,\r\n"
			+ "    0 AS fpy\r\n"
			+ "FROM (\r\n"
			+ "    SELECT 'headcount' AS heading, 'Direct- HC' AS maingroup,\r\n"
			+ "           SUM(CASE WHEN category='Direct' THEN headcount ELSE 0 END) AS bud,\r\n"
			+ "           0 AS act, 0 AS py\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?2 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Common- HC',\r\n"
			+ "           SUM(CASE WHEN category='Common' THEN headcount ELSE 0 END), \r\n"
			+ "           0, 0\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?2 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Direct- CTC',\r\n"
			+ "           SUM(CASE WHEN category='Direct' THEN ctc ELSE 0 END),\r\n"
			+ "           0, 0\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?2 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Common- CTC',\r\n"
			+ "           SUM(CASE WHEN category='Common' THEN ctc ELSE 0 END),\r\n"
			+ "           0, 0\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?2 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Direct- HC',\r\n"
			+ "           0,\r\n"
			+ "           SUM(CASE WHEN category='Direct' THEN headcount ELSE 0 END),\r\n"
			+ "           0\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?2 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Common- HC',\r\n"
			+ "           0,\r\n"
			+ "           SUM(CASE WHEN category='Common' THEN headcount ELSE 0 END),\r\n"
			+ "           0\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?2 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Direct- CTC',\r\n"
			+ "           0,\r\n"
			+ "           SUM(CASE WHEN category='Direct' THEN ctc ELSE 0 END),\r\n"
			+ "           0\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?2 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Common- CTC',\r\n"
			+ "           0,\r\n"
			+ "           SUM(CASE WHEN category='Common' THEN ctc ELSE 0 END),\r\n"
			+ "           0\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?2 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Direct- HC',\r\n"
			+ "           0, 0,\r\n"
			+ "           SUM(CASE WHEN category='Direct' THEN headcount ELSE 0 END)\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?3 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Common- HC',\r\n"
			+ "           0, 0,\r\n"
			+ "           SUM(CASE WHEN category='Common' THEN headcount ELSE 0 END)\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?3 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Direct- CTC',\r\n"
			+ "           0, 0,\r\n"
			+ "           SUM(CASE WHEN category='Direct' THEN ctc ELSE 0 END)\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?3 AND month = ?4 AND LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT 'headcount', 'Common- CTC',\r\n"
			+ "           0, 0,\r\n"
			+ "           SUM(CASE WHEN category='Common' THEN ctc ELSE 0 END)\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE clientcode=?1 AND year=?3 AND month = ?4 and  LENGTH(TRIM(employmenttype)) > 0\r\n"
			+ ") t\r\n"
			+ "GROUP BY t.heading, t.maingroup")
	Set<Object[]> getELSummaryHeadCountReport(String clientCode, String finYear, String previousYear, String month);
	
	
	@Query(nativeQuery = true, value = "select row_number() over() sno,t.heading,t.maingroup,0 bud ,0 act,0 py,sum(t.bud)ybyd,sum(t.act)yact,sum(t.py)ypy,0 fbud, 0 estimate,0 fpy from(\r\n"
			+ "select 'Ratio Analysis'heading,accountname maingroup, amount bud,0 act,0 py from budget where clientcode=?1 and year=?2 and month=?4 and maingroup='Ratio Analysis' and subgroup='Ratio' and accountname in('Current Ratio','ROA (%)','ROE (%)')\r\n"
			+ "union\r\n"
			+ "select 'Ratio Analysis'heading,accountname maingroup, 0 bud,amount act,0 py from previousyearactual where clientcode=?1 and year=?2 and month=?4 and maingroup='Ratio Analysis' and subgroup='Ratio' and accountname in('Current Ratio','ROA (%)','ROE (%)')\r\n"
			+ "union\r\n"
			+ "select 'Ratio Analysis'heading,accountname maingroup, 0 bud,0 act,amount py from previousyearactual where clientcode=?1 and year=?3 and month=?4 and maingroup='Ratio Analysis' and subgroup='Ratio' and accountname in('Current Ratio','ROA (%)','ROE (%)'))t group by t.heading, t.maingroup")
	Set<Object[]> getELSummaryRatioAnalysisReport(String clientCode, String finYear, String previousYear, String month);

}
